[package]
name = "iced_project"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14", features = ["image", "tokio", "advanced", "canvas"] }
matrix-sdk = { version = "0.16.0", features = ["sso-login"] }
url = "2.5.8"
lyon_algorithms = "1.0"
